---

AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: uk.co.bigpicturetech.sampleserverless.HelloWorldHandler
      CodeUri: ./target/sampleserverless-0.1.0-SNAPSHOT.jar
      Runtime: java8
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get